---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04-vmware
    driver_config:
      box: ubuntu-14.04
      box_url: https://nmd-vmware.s3-us-west-2.amazonaws.com/nmd-ubunutu-14.04-x86_64-base.box
  - name: ubuntu-14.04-virtualbox
    driver_config:
      box: ubuntu-14.04
      box_url: https://nmd-virtualbox.s3-us-west-2.amazonaws.com/nmd-ubunutu-14.04-x86_64-base.box
  - name: centos-6.5-vmware
    driver_config:
      box: centos-6.5
      box_url: https://nmd-vmware.s3-us-west-2.amazonaws.com/nmd-centos-6.5-x86_64-base.box
  - name: centos-6.5-virtualbox
    driver_config:
      box: centos-6.5
      box_url: https://nmd-virtualbox.s3-us-west-2.amazonaws.com/nmd-centos-6.5-x86_64-base.box
suites:
  - name: default
    run_list:
      - recipe[git::default]
      - recipe[nmddrupal::drush]
      - recipe[nmddrupal::files]
    attributes:
      nmddrupal:
        sites:
          - example
  - name: drush
    run_list:
      - recipe[git::default]
      - recipe[nmddrupal::drush]
    attributes:
      nmddrupal:
        sites:
          - example
  - name: files
    run_list:
      - recipe[nmddrupal::files]
    attributes:
      nmddrupal:
        sites:
          - example
  - name: deploy
    run_list:
      - recipe[git::default]
      - recipe[nmddrupal::deploy]
    attributes:
      nmddrupal:
        sites:
          example:
            deploy:
              action:
                - deploy
