---
driver:
  name: vagrant
provisioner:
  name: chef_solo
  data_bags_path: test/support/data_bags
  roles_path: chef/sites
  environments_path: chef/environments
platforms:
  - name: ubuntu-12.04
    driver_config:
      box: precise64
      box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box
      provider: virtualbox
      customize:
        memory: 1024
      network:
        - ["private_network", {ip: "192.168.50.5"}]
      use_vagrant_provision: true
      require_chef_omnibus: true
      forward_agent: true
suites:
  - name: default
    run_list:
      - recipe[drupal::default]
    attributes:
      drupal:
        sites:
          example:
            active: 1
            deploy:
              action:
                - deploy
                - install
            repository:
              shallow_clone: true
